export default {
  colon: ':',
  header: {
    joinDc: 'Unirse'
  },
  auth: {
    title: 'Cuenta',
    login: 'Iniciar sesión',
    logout: 'Cerrar sesión',
    signup: 'Registrarse',
    email: 'Dirección de correo electrónico',
    username: 'Nombre de usuario',
    usernameOrEmail: 'Nombre de usuario / dirección de correo electrónico',
    passwd: 'Contraseña',
    veriCode: 'Código de verificación',
    getVeriCode: 'Obtener código de verificación',
    sendingVeriCode: 'Enviando código de verificación...',
    loggingIn: 'Iniciando sesión...',
    alreadyHaveAnAcc: '¿Ya tienes una cuenta?',
    createNewAcc: '¡Crea una nueva cuenta!',
    forgotPw: '¿Olvidaste la contraseña?',
    emailRequired: 'Se requiere la dirección de correo electrónico.',
    emailInvalid: 'El formato de la dirección de correo electrónico no es válido.',
    usernameOrEmailRequired: 'Se requiere un nombre de usuario o una dirección de correo electrónico.',
    usernameRequired: 'Se requiere el nombre de usuario.',
    usernameLength: 'Longitud del nombre de usuario: de 5 a 32 caracteres',
    passwdRequired: 'Se requiere la contraseña.',
    passwdLength: 'Longitud de la contraseña: de 8 a 64 caracteres',
    veriCodeRequired: 'Se requiere el código de verificación.',
    confirmChangeEmail: '¿Estás seguro de que quieres cambiar la dirección de correo electrónico?',
    notReceiveVeriCode: '¿No recibiste el código de verificación?',
    formIncomplete: '¡Formulario incompleto!'
  },
  action: {
    more: 'Más acciones',
    rename: 'Renombrar',
    renameConv: 'Renombrar conversación',
    refresh: 'Actualizar conversación',
    regenerate: 'Regenerar',
    continueGenerate: 'Continuar generando',
    resend: 'Reenviar',
    change: 'Cambiar',
    copy: 'Copiar',
    copySuccess: '¡Copiado!',
    copyFailed: 'Error al copiar.',
    delete: 'Eliminar',
    deleteConv: 'Eliminar conversación',
    exportAs: 'Exportar como',
    newVersion: '¡Se ha lanzado una nueva versión! ¿Deseas recargar la página?',
    opCanceled: 'La operación se ha cancelado.',
    opExecuted: 'La operación se ha ejecutado.',
  },
  message: {
    renameConvHint: 'Por favor, ingresa un título de conversación:',
    renameSuccess: 'La conversación ha sido renombrada.',
    deleteConvConfirm: '¿Estás seguro/a de que deseas eliminar esta conversación? ¡Esta acción no se puede deshacer!',
    deleteMsgConfirm: '¿Eliminar esta pregunta y sus respuestas?',
    notice: 'Aviso',
    warning: 'Advertencia',
    setting: 'Configuración',
    ok: 'Aceptar',
    cancel: 'Cancelar',
    yes: 'Sí',
    no: 'No',
  },
  menu: {
    title: 'Menú',
    about: 'Acerca de',
    joinDcMessage: '¡Únete a nuestro servidor de Discord para estar al día con las últimas noticias de EvoGPT!',
    webInfo1: 'Básico: ',
    webInfo2: 'Permite extraer URL de la pregunta o utilizar un motor de búsqueda para realizar la consulta. ',
    webInfo3: 'Avanzado: ',
   

 webInfo4: 'Permite extraer URL de la pregunta, permitiendo que la IA determine los datos a buscar y proporcione una conclusión después de resumir varias páginas web. ',
    expFeat1: 'Esto lleva un poco de tiempo.',
    expFeat2: 'Esto llevará más tiempo.',
    tempInfo: 'Con valores más altos aumenta la aleatoriedad y diversidad, mientras que con valores más bajos disminuye la aleatoriedad y hace que la salida sea más predecible.',
  },
  settings: {
    title: 'Configuración',
    model: 'Modelo',
    lang: 'Idioma de la interfaz de usuario',
    webBrowsing: 'Navegación web',
    off: 'Desactivado',
    on: 'Activado',
    enable: 'Habilitar',
    disable: 'Deshabilitar',
    basic: 'Básico',
    advanced: 'Avanzado',
    context: 'Contexto',
  },
  chat: {
    chats: 'Conversaciones',
    newChat: 'Nueva conversación',
    letsStart: '¡Empecemos!',
    send: 'Enviar',
  },
  error: {
    qTooLong: 'Pregunta demasiado larga.',
    plzRefresh: 'Por favor, actualiza la página.'
  },
  footer: {
    patient: 'Por favor, ten paciencia. Esto puede llevar algunos minutos.',
  }
}
